services:
  db:
    image: "postgres:13.4"
    container_name: conciliator-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - './volumes/db:/mnt/db'